#include "ui/PlanningPage.h"

#include "core/ArchiveDocument.h"
#include "ui/RelationshipBoard.h"

#include <QCheckBox>
#include <QComboBox>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFrame>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QJsonArray>
#include <QJsonObject>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QMimeDatabase>
#include <QPixmap>
#include <QPushButton>
#include <QScrollArea>
#include <QSpinBox>
#include <QSplitter>
#include <QTabWidget>
#include <QTextEdit>
#include <QUuid>
#include <QVBoxLayout>

namespace wbw {
namespace {

QString uid(const QString& prefix) { return prefix + QLatin1Char('-') + QUuid::createUuid().toString(QUuid::Id128); }
QPushButton* makeButton(const QString& text) { auto* b=new QPushButton(text); b->setCursor(Qt::PointingHandCursor); return b; }
QString jsonStrings(const QJsonArray& a){QStringList v;for(const QJsonValue x:a)if(!x.toString().trimmed().isEmpty())v.append(x.toString().trimmed());return v.join(QStringLiteral(", "));}
QJsonArray stringsJson(const QString& t){QJsonArray r;for(QString v:t.split(QLatin1Char(','),Qt::SkipEmptyParts)){v=v.trimmed();if(!v.isEmpty())r.append(v);}return r;}
QString evidenceText(const QJsonArray& a){QStringList lines;for(const QJsonValue v:a){const QJsonObject o=v.toObject();const QString c=o.value(QStringLiteral("chapter")).toString(),t=o.value(QStringLiteral("text")).toString();lines.append(c.isEmpty()?t:c+QStringLiteral(" | ")+t);}return lines.join(QLatin1Char('\n'));}
QJsonArray textEvidence(const QString& t){QJsonArray r;for(QString line:t.split(QLatin1Char('\n'),Qt::SkipEmptyParts)){line=line.trimmed();if(line.isEmpty())continue;const qsizetype s=line.indexOf(QLatin1Char('|'));r.append(QJsonObject{{QStringLiteral("chapter"),s<0?QString():line.left(s).trimmed()},{QStringLiteral("text"),s<0?line:line.mid(s+1).trimmed()}});}return r;}
QString intArrayText(const QJsonArray& a){QStringList v;for(const QJsonValue x:a)v.append(QString::number(x.toInt()));return v.join(QStringLiteral(", "));}
QJsonArray textIntArray(const QString& t){QJsonArray r;for(const QString& p:t.split(QLatin1Char(','),Qt::SkipEmptyParts)){bool ok=false;const int v=p.trimmed().toInt(&ok);if(ok)r.append(v);}return r;}
void setComboText(QComboBox* c,const QString& v){const int i=c->findText(v);if(i>=0)c->setCurrentIndex(i);else if(!v.isEmpty()){c->addItem(v);c->setCurrentText(v);}}
void setComboData(QComboBox* c,const QString& v){const int i=c->findData(v);c->setCurrentIndex(i>=0?i:0);}
QByteArray dataUrlBytes(const QString& d){const qsizetype comma=d.indexOf(QLatin1Char(','));if(!d.startsWith(QStringLiteral("data:"),Qt::CaseInsensitive)||comma<0)return{};const QString meta=d.mid(5,comma-5);const QByteArray b=d.mid(comma+1).toLatin1();return meta.contains(QStringLiteral(";base64"),Qt::CaseInsensitive)?QByteArray::fromBase64(b):QByteArray::fromPercentEncoding(b);}
QWidget* fieldBlock(const QString& title,QWidget* field){auto* w=new QWidget;auto* l=new QVBoxLayout(w);l->setContentsMargins(0,0,0,0);l->setSpacing(5);auto* label=new QLabel(title);label->setObjectName(QStringLiteral("planningField"));l->addWidget(label);l->addWidget(field);return w;}
QFrame* card(const QString& title,QLayout* body){auto* f=new QFrame;f->setObjectName(QStringLiteral("planningCard"));auto* l=new QVBoxLayout(f);l->setContentsMargins(16,14,16,16);l->setSpacing(10);auto* h=new QLabel(title);h->setObjectName(QStringLiteral("planningCardTitle"));l->addWidget(h);l->addLayout(body);return f;}
QTextEdit* compactText(int height=100){auto* e=new QTextEdit;e->setMaximumHeight(height);return e;}

} // namespace

PlanningPage::PlanningPage(QWidget* parent):QWidget(parent){
    setObjectName(QStringLiteral("planningPage"));
    auto* root=new QVBoxLayout(this);root->setContentsMargins(0,0,0,0);
    tabs_=new QTabWidget;tabs_->setObjectName(QStringLiteral("planningTabs"));
    tabs_->addTab(buildCharactersTab(),tr("Personajes"));tabs_->addTab(buildBoardTab(),tr("Tablero y relaciones"));tabs_->addTab(buildTheoriesTab(),tr("Hilos / teorías"));tabs_->addTab(buildTimelineTab(),tr("Cronología"));root->addWidget(tabs_);
    setStyleSheet(QStringLiteral(
        "#planningPage{background:#edf1f5;}#planningTabs::pane{border:0;background:#edf1f5;}"
        "#planningCharacters,#planningBoard,#planningTheories,#planningTimeline{background:#edf1f5;}"
        "#planningIndex,#planningEditor,#planningRelationPanel{background:#fff;border:1px solid #d5dce5;}"
        "#planningHero{background:#f5f8fc;border:1px solid #d7dee8;}"
        "#planningKicker,#planningField,#planningIndexTitle{color:#667085;font-size:8pt;font-weight:700;letter-spacing:.6px;}"
        "#planningTitle{font-family:'Georgia';font-size:25pt;color:#344054;}"
        "#planningDescription{font-family:'Georgia';color:#667085;}"
        "#planningCard{background:#fff;border:1px solid #d5dce5;}#planningCardTitle{font-family:'Georgia';font-size:14pt;color:#344054;}"
        "#characterImage{background:#f8fafc;border:1px solid #d8dee7;color:#667085;}"
        "#planningPrimary{background:#1668d4;color:white;border:1px solid #1668d4;font-weight:600;}"
    ));
}

void PlanningPage::setDocument(ArchiveDocument* document){document_=document;refresh();}

QWidget* PlanningPage::buildCharactersTab(){
    auto* tab=new QWidget;tab->setObjectName(QStringLiteral("planningCharacters"));auto* outer=new QVBoxLayout(tab);outer->setContentsMargins(30,22,30,30);outer->setSpacing(14);
    auto* hero=new QFrame;hero->setObjectName(QStringLiteral("planningHero"));auto* hv=new QVBoxLayout(hero);auto* k=new QLabel(tr("PERSONAJES / EVIDENCIAS / PRESENCIA"));k->setObjectName(QStringLiteral("planningKicker"));auto* t=new QLabel(tr("Personajes"));t->setObjectName(QStringLiteral("planningTitle"));auto* d=new QLabel(tr("Fichas narrativas, presencia y relaciones del reparto."));d->setObjectName(QStringLiteral("planningDescription"));hv->addWidget(k);hv->addWidget(t);hv->addWidget(d);outer->addWidget(hero);
    auto* split=new QSplitter;split->setChildrenCollapsible(false);split->setHandleWidth(8);
    auto* left=new QWidget;left->setObjectName(QStringLiteral("planningIndex"));auto* ll=new QVBoxLayout(left);ll->setContentsMargins(12,12,12,12);auto* lt=new QLabel(tr("REPARTO"));lt->setObjectName(QStringLiteral("planningIndexTitle"));ll->addWidget(lt);characterList_=new QListWidget;characterList_->setMinimumWidth(220);characterList_->setMaximumWidth(330);ll->addWidget(characterList_,1);auto* la=new QHBoxLayout;auto* add=makeButton(tr("+ Personaje"));add->setObjectName(QStringLiteral("planningPrimary"));auto* remove=makeButton(tr("Eliminar"));la->addWidget(add,1);la->addWidget(remove);ll->addLayout(la);split->addWidget(left);
    auto* scroll=new QScrollArea;scroll->setWidgetResizable(true);scroll->setFrameShape(QFrame::NoFrame);auto* editor=new QWidget;editor->setObjectName(QStringLiteral("planningEditor"));auto* ev=new QVBoxLayout(editor);ev->setContentsMargins(16,14,16,18);ev->setSpacing(12);
    auto* top=new QHBoxLayout;characterImage_=new QLabel(tr("Sin imagen"));characterImage_->setObjectName(QStringLiteral("characterImage"));characterImage_->setMinimumSize(190,150);characterImage_->setMaximumSize(250,190);characterImage_->setAlignment(Qt::AlignCenter);auto* imageButton=makeButton(tr("Elegir imagen…"));auto* imageCol=new QVBoxLayout;imageCol->addWidget(characterImage_);imageCol->addWidget(imageButton);imageCol->addStretch();top->addLayout(imageCol);
    characterName_=new QLineEdit;characterAliases_=new QLineEdit;characterAliases_->setPlaceholderText(tr("Alias separados por comas"));characterCategory_=new QComboBox;characterCategory_->addItems({tr("Principal"),tr("Secundario"),tr("Incidental"),tr("Histórico"),tr("Entidad")});characterStatus_=new QComboBox;characterStatus_->addItems({tr("Activo"),tr("Muerto"),tr("Desconocido"),tr("Histórico"),tr("Entidad")});characterRole_=new QLineEdit;characterOccupation_=new QLineEdit;characterOrigin_=new QLineEdit;characterAffiliation_=new QLineEdit;
    auto* identity=new QGridLayout;identity->setHorizontalSpacing(10);identity->setVerticalSpacing(9);identity->addWidget(fieldBlock(tr("Nombre"),characterName_),0,0,1,2);identity->addWidget(fieldBlock(tr("Categoría"),characterCategory_),1,0);identity->addWidget(fieldBlock(tr("Estado"),characterStatus_),1,1);identity->addWidget(fieldBlock(tr("Rol"),characterRole_),2,0);identity->addWidget(fieldBlock(tr("Ocupación"),characterOccupation_),2,1);identity->addWidget(fieldBlock(tr("Origen"),characterOrigin_),3,0);identity->addWidget(fieldBlock(tr("Afiliación"),characterAffiliation_),3,1);identity->addWidget(fieldBlock(tr("Alias"),characterAliases_),4,0,1,2);top->addLayout(identity,1);ev->addLayout(top);
    characterSummary_=compactText(100);characterBackground_=compactText(130);characterPhysical_=compactText(110);characterTraits_=new QLineEdit;characterTraits_->setPlaceholderText(tr("Rasgos separados por comas"));characterEvidence_=compactText(120);characterEvidence_->setPlaceholderText(tr("Capítulo | evidencia, una por línea"));characterPresence_=new QLineEdit;characterPresence_->setPlaceholderText(tr("0, 4, 12…"));characterColor_=new QLineEdit;characterBoardVisible_=new QCheckBox(tr("Mostrar en el tablero"));
    auto* narrative=new QGridLayout;narrative->setHorizontalSpacing(12);narrative->setVerticalSpacing(10);narrative->addWidget(fieldBlock(tr("Resumen"),characterSummary_),0,0);narrative->addWidget(fieldBlock(tr("Descripción física"),characterPhysical_),0,1);narrative->addWidget(fieldBlock(tr("Trasfondo"),characterBackground_),1,0,1,2);narrative->addWidget(fieldBlock(tr("Rasgos"),characterTraits_),2,0);narrative->addWidget(fieldBlock(tr("Presencia por capítulo"),characterPresence_),2,1);narrative->addWidget(fieldBlock(tr("Evidencias"),characterEvidence_),3,0,1,2);narrative->addWidget(fieldBlock(tr("Color"),characterColor_),4,0);narrative->addWidget(characterBoardVisible_,4,1,Qt::AlignBottom);ev->addWidget(card(tr("Ficha narrativa"),narrative));ev->addStretch();scroll->setWidget(editor);split->addWidget(scroll);split->setStretchFactor(1,1);split->setSizes({270,1050});outer->addWidget(split,1);
    connect(characterList_,&QListWidget::currentRowChanged,this,&PlanningPage::selectCharacter);connect(imageButton,&QPushButton::clicked,this,&PlanningPage::chooseCharacterImage);connect(add,&QPushButton::clicked,this,&PlanningPage::addCharacter);connect(remove,&QPushButton::clicked,this,&PlanningPage::removeCharacter);
    for(QLineEdit* f:{characterName_,characterAliases_,characterRole_,characterOccupation_,characterOrigin_,characterAffiliation_,characterTraits_,characterPresence_,characterColor_})connect(f,&QLineEdit::editingFinished,this,&PlanningPage::applyCharacter);for(QTextEdit* f:{characterSummary_,characterBackground_,characterPhysical_,characterEvidence_})connect(f,&QTextEdit::textChanged,this,&PlanningPage::applyCharacter);connect(characterCategory_,&QComboBox::currentTextChanged,this,&PlanningPage::applyCharacter);connect(characterStatus_,&QComboBox::currentTextChanged,this,&PlanningPage::applyCharacter);connect(characterBoardVisible_,&QCheckBox::toggled,this,&PlanningPage::applyCharacter);return tab;
}

QWidget* PlanningPage::buildBoardTab(){
    auto* tab=new QWidget;tab->setObjectName(QStringLiteral("planningBoard"));auto* layout=new QVBoxLayout(tab);layout->setContentsMargins(30,22,30,30);layout->setSpacing(12);auto* top=new QHBoxLayout;auto* all=makeButton(tr("Ver red completa"));auto* focus=makeButton(tr("Enfocar origen"));top->addWidget(all);top->addWidget(focus);top->addStretch();layout->addLayout(top);
    auto* vertical=new QSplitter(Qt::Vertical);board_=new RelationshipBoard;vertical->addWidget(board_);auto* relationPanel=new QWidget;relationPanel->setObjectName(QStringLiteral("planningRelationPanel"));auto* relationLayout=new QHBoxLayout(relationPanel);relationLayout->setContentsMargins(12,12,12,12);relationshipList_=new QListWidget;relationshipList_->setMinimumWidth(280);relationLayout->addWidget(relationshipList_);
    auto* grid=new QGridLayout;relationshipSource_=new QComboBox;relationshipTarget_=new QComboBox;relationshipType_=new QComboBox;relationshipType_->addItems({tr("Familia"),tr("Enemigo"),tr("Conocido"),tr("Solo interactuaron"),tr("Amistad"),tr("Alianza"),tr("Conflicto"),tr("Investigación"),tr("Tutela"),tr("Romance"),tr("Sospecha"),tr("Trabajo"),tr("Culto")});relationshipLabel_=new QLineEdit;relationshipCertainty_=new QComboBox;relationshipCertainty_->addItems({tr("Hecho"),tr("Hipótesis")});relationshipStrength_=new QSpinBox;relationshipStrength_->setRange(1,3);relationshipDetails_=compactText(90);
    grid->addWidget(fieldBlock(tr("Origen"),relationshipSource_),0,0);grid->addWidget(fieldBlock(tr("Destino"),relationshipTarget_),0,1);grid->addWidget(fieldBlock(tr("Tipo"),relationshipType_),1,0);grid->addWidget(fieldBlock(tr("Etiqueta"),relationshipLabel_),1,1);grid->addWidget(fieldBlock(tr("Certeza"),relationshipCertainty_),2,0);grid->addWidget(fieldBlock(tr("Fortaleza"),relationshipStrength_),2,1);grid->addWidget(fieldBlock(tr("Detalle"),relationshipDetails_),3,0,1,2);auto* actions=new QHBoxLayout;auto* add=makeButton(tr("+ Relación"));auto* remove=makeButton(tr("Eliminar"));actions->addWidget(add);actions->addWidget(remove);actions->addStretch();grid->addLayout(actions,4,0,1,2);relationLayout->addLayout(grid,1);vertical->addWidget(relationPanel);vertical->setStretchFactor(0,3);vertical->setStretchFactor(1,2);layout->addWidget(vertical,1);
    connect(all,&QPushButton::clicked,board_,&RelationshipBoard::showAllCharacters);connect(focus,&QPushButton::clicked,this,[this](){const QString id=relationshipSource_->currentData().toString();if(!id.isEmpty())board_->focusCharacter(id);});connect(board_,&RelationshipBoard::characterMoved,this,&PlanningPage::moveCharacter);connect(board_,&RelationshipBoard::characterActivated,this,[this](const QString& id){if(!document_)return;const QJsonArray a=document_->array(QStringLiteral("characters"));for(int i=0;i<a.size();++i)if(a.at(i).toObject().value(QStringLiteral("id")).toString()==id){tabs_->setCurrentIndex(0);characterList_->setCurrentRow(i);break;}});connect(relationshipList_,&QListWidget::currentRowChanged,this,&PlanningPage::selectRelationship);connect(add,&QPushButton::clicked,this,&PlanningPage::addRelationship);connect(remove,&QPushButton::clicked,this,&PlanningPage::removeRelationship);connect(relationshipSource_,&QComboBox::currentIndexChanged,this,&PlanningPage::applyRelationship);connect(relationshipTarget_,&QComboBox::currentIndexChanged,this,&PlanningPage::applyRelationship);connect(relationshipType_,&QComboBox::currentTextChanged,this,&PlanningPage::applyRelationship);connect(relationshipLabel_,&QLineEdit::editingFinished,this,&PlanningPage::applyRelationship);connect(relationshipCertainty_,&QComboBox::currentTextChanged,this,&PlanningPage::applyRelationship);connect(relationshipStrength_,&QSpinBox::valueChanged,this,&PlanningPage::applyRelationship);connect(relationshipDetails_,&QTextEdit::textChanged,this,&PlanningPage::applyRelationship);return tab;
}

QWidget* PlanningPage::buildTheoriesTab(){
    auto* tab=new QWidget;tab->setObjectName(QStringLiteral("planningTheories"));auto* layout=new QVBoxLayout(tab);layout->setContentsMargins(30,22,30,30);auto* split=new QSplitter;split->setChildrenCollapsible(false);auto* left=new QWidget;left->setObjectName(QStringLiteral("planningIndex"));auto* ll=new QVBoxLayout(left);auto* title=new QLabel(tr("HILOS / TEORÍAS"));title->setObjectName(QStringLiteral("planningIndexTitle"));ll->addWidget(title);theoryList_=new QListWidget;theoryList_->setMinimumWidth(240);ll->addWidget(theoryList_,1);auto* actions=new QHBoxLayout;auto* add=makeButton(tr("+ Teoría"));auto* remove=makeButton(tr("Eliminar"));actions->addWidget(add,1);actions->addWidget(remove);ll->addLayout(actions);split->addWidget(left);
    auto* editor=new QWidget;editor->setObjectName(QStringLiteral("planningEditor"));auto* ev=new QVBoxLayout(editor);ev->setContentsMargins(16,14,16,18);theoryTitle_=new QLineEdit;theoryStatus_=new QComboBox;theoryStatus_->addItems({tr("Confirmada"),tr("Muy probable"),tr("Abierta"),tr("Descartada")});theoryConfidence_=new QSpinBox;theoryConfidence_->setRange(0,100);theoryConfidence_->setSuffix(QStringLiteral(" %"));theoryThesis_=compactText(130);theoryEvidence_=compactText(150);theoryCounterpoint_=compactText(120);theoryCharacters_=new QLineEdit;theoryTags_=new QLineEdit;theoryEvidence_->setPlaceholderText(tr("Capítulo | evidencia, una por línea"));theoryCharacters_->setPlaceholderText(tr("IDs separados por comas"));theoryTags_->setPlaceholderText(tr("Etiquetas separadas por comas"));auto* g=new QGridLayout;g->setHorizontalSpacing(12);g->setVerticalSpacing(10);g->addWidget(fieldBlock(tr("Título"),theoryTitle_),0,0,1,2);g->addWidget(fieldBlock(tr("Estado"),theoryStatus_),1,0);g->addWidget(fieldBlock(tr("Confianza"),theoryConfidence_),1,1);g->addWidget(fieldBlock(tr("Tesis"),theoryThesis_),2,0,1,2);g->addWidget(fieldBlock(tr("Evidencias"),theoryEvidence_),3,0);g->addWidget(fieldBlock(tr("Contraargumento"),theoryCounterpoint_),3,1);g->addWidget(fieldBlock(tr("Personajes"),theoryCharacters_),4,0);g->addWidget(fieldBlock(tr("Etiquetas"),theoryTags_),4,1);ev->addWidget(card(tr("Hipótesis"),g));ev->addStretch();split->addWidget(editor);split->setStretchFactor(1,1);layout->addWidget(split);
    connect(theoryList_,&QListWidget::currentRowChanged,this,&PlanningPage::selectTheory);connect(add,&QPushButton::clicked,this,&PlanningPage::addTheory);connect(remove,&QPushButton::clicked,this,&PlanningPage::removeTheory);connect(theoryTitle_,&QLineEdit::editingFinished,this,&PlanningPage::applyTheory);connect(theoryStatus_,&QComboBox::currentTextChanged,this,&PlanningPage::applyTheory);connect(theoryConfidence_,&QSpinBox::valueChanged,this,&PlanningPage::applyTheory);connect(theoryThesis_,&QTextEdit::textChanged,this,&PlanningPage::applyTheory);connect(theoryEvidence_,&QTextEdit::textChanged,this,&PlanningPage::applyTheory);connect(theoryCounterpoint_,&QTextEdit::textChanged,this,&PlanningPage::applyTheory);connect(theoryCharacters_,&QLineEdit::editingFinished,this,&PlanningPage::applyTheory);connect(theoryTags_,&QLineEdit::editingFinished,this,&PlanningPage::applyTheory);return tab;
}

QWidget* PlanningPage::buildTimelineTab(){
    auto* tab=new QWidget;tab->setObjectName(QStringLiteral("planningTimeline"));auto* layout=new QVBoxLayout(tab);layout->setContentsMargins(30,22,30,30);auto* split=new QSplitter;split->setChildrenCollapsible(false);auto* left=new QWidget;left->setObjectName(QStringLiteral("planningIndex"));auto* ll=new QVBoxLayout(left);auto* title=new QLabel(tr("CRONOLOGÍA"));title->setObjectName(QStringLiteral("planningIndexTitle"));ll->addWidget(title);timelineList_=new QListWidget;timelineList_->setMinimumWidth(260);ll->addWidget(timelineList_,1);auto* actions=new QHBoxLayout;auto* add=makeButton(tr("+ Evento"));auto* remove=makeButton(tr("Eliminar"));auto* up=makeButton(tr("↑"));auto* down=makeButton(tr("↓"));actions->addWidget(add,1);actions->addWidget(remove);actions->addWidget(up);actions->addWidget(down);ll->addLayout(actions);split->addWidget(left);
    auto* editor=new QWidget;editor->setObjectName(QStringLiteral("planningEditor"));auto* ev=new QVBoxLayout(editor);ev->setContentsMargins(16,14,16,18);timelineChapter_=new QLineEdit;timelineWhen_=new QLineEdit;timelineTitle_=new QLineEdit;timelineSummary_=compactText(170);timelineCharacters_=new QLineEdit;timelineCharacters_->setPlaceholderText(tr("IDs separados por comas"));timelineIntensity_=new QSpinBox;timelineIntensity_->setRange(0,10);auto* g=new QGridLayout;g->setHorizontalSpacing(12);g->setVerticalSpacing(10);g->addWidget(fieldBlock(tr("Capítulo"),timelineChapter_),0,0);g->addWidget(fieldBlock(tr("Cuándo"),timelineWhen_),0,1);g->addWidget(fieldBlock(tr("Título"),timelineTitle_),1,0,1,2);g->addWidget(fieldBlock(tr("Resumen"),timelineSummary_),2,0,1,2);g->addWidget(fieldBlock(tr("Personajes"),timelineCharacters_),3,0);g->addWidget(fieldBlock(tr("Intensidad"),timelineIntensity_),3,1);ev->addWidget(card(tr("Evento"),g));ev->addStretch();split->addWidget(editor);split->setStretchFactor(1,1);layout->addWidget(split);
    connect(timelineList_,&QListWidget::currentRowChanged,this,&PlanningPage::selectTimeline);connect(add,&QPushButton::clicked,this,&PlanningPage::addTimeline);connect(remove,&QPushButton::clicked,this,&PlanningPage::removeTimeline);connect(up,&QPushButton::clicked,this,[this](){if(!document_)return;const int row=timelineList_->currentRow();if(row<=0)return;QJsonArray a=document_->array(QStringLiteral("timeline"));const QJsonValue v=a.takeAt(row);a.insert(row-1,v);document_->setArray(QStringLiteral("timeline"),a);refreshTimeline();timelineList_->setCurrentRow(row-1);emit changed();});connect(down,&QPushButton::clicked,this,[this](){if(!document_)return;const int row=timelineList_->currentRow();QJsonArray a=document_->array(QStringLiteral("timeline"));if(row<0||row>=a.size()-1)return;const QJsonValue v=a.takeAt(row);a.insert(row+1,v);document_->setArray(QStringLiteral("timeline"),a);refreshTimeline();timelineList_->setCurrentRow(row+1);emit changed();});connect(timelineChapter_,&QLineEdit::editingFinished,this,&PlanningPage::applyTimeline);connect(timelineWhen_,&QLineEdit::editingFinished,this,&PlanningPage::applyTimeline);connect(timelineTitle_,&QLineEdit::editingFinished,this,&PlanningPage::applyTimeline);connect(timelineSummary_,&QTextEdit::textChanged,this,&PlanningPage::applyTimeline);connect(timelineCharacters_,&QLineEdit::editingFinished,this,&PlanningPage::applyTimeline);connect(timelineIntensity_,&QSpinBox::valueChanged,this,&PlanningPage::applyTimeline);return tab;
}

void PlanningPage::refresh(){if(!document_)return;refreshing_=true;refreshCharacters();refreshRelationships();refreshTheories();refreshTimeline();refreshing_=false;if(characterList_->count())characterList_->setCurrentRow(0);if(relationshipList_->count())relationshipList_->setCurrentRow(0);if(theoryList_->count())theoryList_->setCurrentRow(0);if(timelineList_->count())timelineList_->setCurrentRow(0);}
void PlanningPage::refreshCharacters(){characterList_->clear();relationshipSource_->clear();relationshipTarget_->clear();relationshipSource_->addItem(tr("—"),QString());relationshipTarget_->addItem(tr("—"),QString());const QJsonArray a=document_->array(QStringLiteral("characters"));for(const QJsonValue v:a){const QJsonObject c=v.toObject();const QString n=c.value(QStringLiteral("name")).toString(tr("Personaje sin nombre")),id=c.value(QStringLiteral("id")).toString();characterList_->addItem(n);relationshipSource_->addItem(n,id);relationshipTarget_->addItem(n,id);}board_->setData(a,document_->array(QStringLiteral("relationships")));}
void PlanningPage::selectCharacter(int row){if(!document_)return;refreshing_=true;const QJsonArray a=document_->array(QStringLiteral("characters"));const QJsonObject o=row>=0&&row<a.size()?a.at(row).toObject():QJsonObject();characterName_->setText(o.value(QStringLiteral("name")).toString());characterAliases_->setText(jsonStrings(o.value(QStringLiteral("aliases")).toArray()));setComboText(characterCategory_,o.value(QStringLiteral("category")).toString());setComboText(characterStatus_,o.value(QStringLiteral("status")).toString());characterRole_->setText(o.value(QStringLiteral("role")).toString());characterOccupation_->setText(o.value(QStringLiteral("occupation")).toString());characterOrigin_->setText(o.value(QStringLiteral("origin")).toString());characterAffiliation_->setText(o.value(QStringLiteral("affiliation")).toString());characterSummary_->setPlainText(o.value(QStringLiteral("summary")).toString());characterBackground_->setPlainText(o.value(QStringLiteral("background")).toString());characterPhysical_->setPlainText(o.value(QStringLiteral("physical")).toString());characterTraits_->setText(jsonStrings(o.value(QStringLiteral("traits")).toArray()));characterEvidence_->setPlainText(evidenceText(o.value(QStringLiteral("evidence")).toArray()));characterPresence_->setText(intArrayText(o.value(QStringLiteral("presence")).toArray()));characterColor_->setText(o.value(QStringLiteral("color")).toString());const QJsonObject b=o.value(QStringLiteral("board")).toObject();characterBoardVisible_->setChecked(!b.contains(QStringLiteral("visible"))||b.value(QStringLiteral("visible")).toBool(true));const QByteArray image=dataUrlBytes(o.value(QStringLiteral("imageUrl")).toString());QPixmap pix;if(!image.isEmpty())pix.loadFromData(image);if(pix.isNull()){characterImage_->setPixmap(QPixmap());characterImage_->setText(tr("Sin imagen"));}else{characterImage_->setText(QString());characterImage_->setPixmap(pix.scaled(characterImage_->size(),Qt::KeepAspectRatio,Qt::SmoothTransformation));}refreshing_=false;}
void PlanningPage::applyCharacter(){if(refreshing_||!document_)return;const int row=characterList_->currentRow();QJsonArray a=document_->array(QStringLiteral("characters"));if(row<0||row>=a.size())return;QJsonObject o=a.at(row).toObject();o.insert(QStringLiteral("name"),characterName_->text());o.insert(QStringLiteral("aliases"),stringsJson(characterAliases_->text()));o.insert(QStringLiteral("category"),characterCategory_->currentText());o.insert(QStringLiteral("status"),characterStatus_->currentText());o.insert(QStringLiteral("role"),characterRole_->text());o.insert(QStringLiteral("occupation"),characterOccupation_->text());o.insert(QStringLiteral("origin"),characterOrigin_->text());o.insert(QStringLiteral("affiliation"),characterAffiliation_->text());o.insert(QStringLiteral("summary"),characterSummary_->toPlainText());o.insert(QStringLiteral("background"),characterBackground_->toPlainText());o.insert(QStringLiteral("physical"),characterPhysical_->toPlainText());o.insert(QStringLiteral("traits"),stringsJson(characterTraits_->text()));o.insert(QStringLiteral("evidence"),textEvidence(characterEvidence_->toPlainText()));o.insert(QStringLiteral("presence"),textIntArray(characterPresence_->text()));o.insert(QStringLiteral("color"),characterColor_->text());QJsonObject b=o.value(QStringLiteral("board")).toObject();if(!b.contains(QStringLiteral("x")))b.insert(QStringLiteral("x"),100.0+row*40.0);if(!b.contains(QStringLiteral("y")))b.insert(QStringLiteral("y"),100.0+row*35.0);b.insert(QStringLiteral("visible"),characterBoardVisible_->isChecked());o.insert(QStringLiteral("board"),b);a.replace(row,o);document_->setArray(QStringLiteral("characters"),a);characterList_->item(row)->setText(characterName_->text().isEmpty()?tr("Personaje sin nombre"):characterName_->text());board_->setData(a,document_->array(QStringLiteral("relationships")));emit changed();}
void PlanningPage::chooseCharacterImage(){if(!document_)return;const int row=characterList_->currentRow();if(row<0)return;const QString path=QFileDialog::getOpenFileName(this,tr("Imagen del personaje"),QString(),tr("Imágenes (*.png *.jpg *.jpeg *.webp *.gif)"));if(path.isEmpty())return;QFile file(path);if(!file.open(QIODevice::ReadOnly))return;const QByteArray bytes=file.readAll();const QString mime=QMimeDatabase().mimeTypeForFile(path,QMimeDatabase::MatchContent).name();QJsonArray a=document_->array(QStringLiteral("characters"));QJsonObject o=a.at(row).toObject();o.insert(QStringLiteral("imageUrl"),QStringLiteral("data:%1;base64,%2").arg(mime,QString::fromLatin1(bytes.toBase64())));a.replace(row,o);document_->setArray(QStringLiteral("characters"),a);selectCharacter(row);emit changed();}
void PlanningPage::addCharacter(){if(!document_)return;QJsonArray a=document_->array(QStringLiteral("characters"));a.append(QJsonObject{{QStringLiteral("id"),uid(QStringLiteral("character"))},{QStringLiteral("name"),tr("Personaje sin nombre")},{QStringLiteral("aliases"),QJsonArray()},{QStringLiteral("category"),tr("Secundario")},{QStringLiteral("status"),tr("Activo")},{QStringLiteral("role"),QString()},{QStringLiteral("occupation"),QString()},{QStringLiteral("origin"),QString()},{QStringLiteral("affiliation"),QString()},{QStringLiteral("summary"),QString()},{QStringLiteral("background"),QString()},{QStringLiteral("physical"),QString()},{QStringLiteral("traits"),QJsonArray()},{QStringLiteral("evidence"),QJsonArray()},{QStringLiteral("presence"),QJsonArray()},{QStringLiteral("color"),QStringLiteral("amber")},{QStringLiteral("board"),QJsonObject{{QStringLiteral("x"),120.0+a.size()*30.0},{QStringLiteral("y"),120.0+a.size()*25.0},{QStringLiteral("visible"),true}}}});document_->setArray(QStringLiteral("characters"),a);refreshCharacters();characterList_->setCurrentRow(a.size()-1);refreshRelationships();emit changed();}
void PlanningPage::removeCharacter(){if(!document_)return;const int row=characterList_->currentRow();QJsonArray a=document_->array(QStringLiteral("characters"));if(row<0||row>=a.size())return;const QString id=a.at(row).toObject().value(QStringLiteral("id")).toString();a.removeAt(row);QJsonArray r=document_->array(QStringLiteral("relationships"));for(int i=r.size()-1;i>=0;--i){const QJsonObject o=r.at(i).toObject();if(o.value(QStringLiteral("source")).toString()==id||o.value(QStringLiteral("target")).toString()==id)r.removeAt(i);}document_->setArray(QStringLiteral("characters"),a);document_->setArray(QStringLiteral("relationships"),r);refreshCharacters();refreshRelationships();if(characterList_->count())characterList_->setCurrentRow(qMin(row,characterList_->count()-1));emit changed();}
void PlanningPage::refreshRelationships(){relationshipList_->clear();const QJsonArray r=document_->array(QStringLiteral("relationships"));QHash<QString,QString> names;for(const QJsonValue v:document_->array(QStringLiteral("characters")))names.insert(v.toObject().value(QStringLiteral("id")).toString(),v.toObject().value(QStringLiteral("name")).toString());for(const QJsonValue v:r){const QJsonObject o=v.toObject();relationshipList_->addItem(QStringLiteral("%1 → %2 · %3").arg(names.value(o.value(QStringLiteral("source")).toString(),tr("?")),names.value(o.value(QStringLiteral("target")).toString(),tr("?")),o.value(QStringLiteral("type")).toString()));}board_->setData(document_->array(QStringLiteral("characters")),r);}
void PlanningPage::selectRelationship(int row){if(!document_)return;refreshing_=true;const QJsonArray a=document_->array(QStringLiteral("relationships"));const QJsonObject o=row>=0&&row<a.size()?a.at(row).toObject():QJsonObject();setComboData(relationshipSource_,o.value(QStringLiteral("source")).toString());setComboData(relationshipTarget_,o.value(QStringLiteral("target")).toString());setComboText(relationshipType_,o.value(QStringLiteral("type")).toString());relationshipLabel_->setText(o.value(QStringLiteral("label")).toString());setComboText(relationshipCertainty_,o.value(QStringLiteral("certainty")).toString());relationshipStrength_->setValue(o.value(QStringLiteral("strength")).toInt(1));relationshipDetails_->setPlainText(o.value(QStringLiteral("details")).toString());refreshing_=false;}
void PlanningPage::applyRelationship(){if(refreshing_||!document_)return;const int row=relationshipList_->currentRow();QJsonArray a=document_->array(QStringLiteral("relationships"));if(row<0||row>=a.size())return;QJsonObject o=a.at(row).toObject();o.insert(QStringLiteral("source"),relationshipSource_->currentData().toString());o.insert(QStringLiteral("target"),relationshipTarget_->currentData().toString());o.insert(QStringLiteral("type"),relationshipType_->currentText());o.insert(QStringLiteral("label"),relationshipLabel_->text());o.insert(QStringLiteral("certainty"),relationshipCertainty_->currentText());o.insert(QStringLiteral("strength"),relationshipStrength_->value());o.insert(QStringLiteral("details"),relationshipDetails_->toPlainText());a.replace(row,o);document_->setArray(QStringLiteral("relationships"),a);refreshRelationships();relationshipList_->setCurrentRow(row);emit changed();}
void PlanningPage::addRelationship(){if(!document_)return;const QJsonArray c=document_->array(QStringLiteral("characters"));if(c.size()<2)return;QJsonArray a=document_->array(QStringLiteral("relationships"));a.append(QJsonObject{{QStringLiteral("id"),uid(QStringLiteral("relationship"))},{QStringLiteral("source"),c.at(0).toObject().value(QStringLiteral("id"))},{QStringLiteral("target"),c.at(1).toObject().value(QStringLiteral("id"))},{QStringLiteral("type"),tr("Conocido")},{QStringLiteral("label"),QString()},{QStringLiteral("certainty"),tr("Hecho")},{QStringLiteral("strength"),1},{QStringLiteral("details"),QString()}});document_->setArray(QStringLiteral("relationships"),a);refreshRelationships();relationshipList_->setCurrentRow(a.size()-1);emit changed();}
void PlanningPage::removeRelationship(){if(!document_)return;const int row=relationshipList_->currentRow();QJsonArray a=document_->array(QStringLiteral("relationships"));if(row<0||row>=a.size())return;a.removeAt(row);document_->setArray(QStringLiteral("relationships"),a);refreshRelationships();if(relationshipList_->count())relationshipList_->setCurrentRow(qMin(row,relationshipList_->count()-1));emit changed();}
void PlanningPage::moveCharacter(const QString& id,double x,double y){if(refreshing_||!document_)return;QJsonArray a=document_->array(QStringLiteral("characters"));for(int i=0;i<a.size();++i){QJsonObject c=a.at(i).toObject();if(c.value(QStringLiteral("id")).toString()!=id)continue;QJsonObject b=c.value(QStringLiteral("board")).toObject();if(qAbs(b.value(QStringLiteral("x")).toDouble()-x)<.01&&qAbs(b.value(QStringLiteral("y")).toDouble()-y)<.01)return;b.insert(QStringLiteral("x"),x);b.insert(QStringLiteral("y"),y);c.insert(QStringLiteral("board"),b);a.replace(i,c);document_->setArray(QStringLiteral("characters"),a);emit changed();return;}}
void PlanningPage::refreshTheories(){theoryList_->clear();for(const QJsonValue v:document_->array(QStringLiteral("theories")))theoryList_->addItem(v.toObject().value(QStringLiteral("title")).toString(tr("Teoría sin título")));}
void PlanningPage::selectTheory(int row){if(!document_)return;refreshing_=true;const QJsonArray a=document_->array(QStringLiteral("theories"));const QJsonObject o=row>=0&&row<a.size()?a.at(row).toObject():QJsonObject();theoryTitle_->setText(o.value(QStringLiteral("title")).toString());setComboText(theoryStatus_,o.value(QStringLiteral("status")).toString());theoryConfidence_->setValue(o.value(QStringLiteral("confidence")).toInt());theoryThesis_->setPlainText(o.value(QStringLiteral("thesis")).toString());theoryEvidence_->setPlainText(evidenceText(o.value(QStringLiteral("evidence")).toArray()));theoryCounterpoint_->setPlainText(o.value(QStringLiteral("counterpoint")).toString());theoryCharacters_->setText(jsonStrings(o.value(QStringLiteral("characterIds")).toArray()));theoryTags_->setText(jsonStrings(o.value(QStringLiteral("tags")).toArray()));refreshing_=false;}
void PlanningPage::applyTheory(){if(refreshing_||!document_)return;const int row=theoryList_->currentRow();QJsonArray a=document_->array(QStringLiteral("theories"));if(row<0||row>=a.size())return;QJsonObject o=a.at(row).toObject();o.insert(QStringLiteral("title"),theoryTitle_->text());o.insert(QStringLiteral("status"),theoryStatus_->currentText());o.insert(QStringLiteral("confidence"),theoryConfidence_->value());o.insert(QStringLiteral("thesis"),theoryThesis_->toPlainText());o.insert(QStringLiteral("evidence"),textEvidence(theoryEvidence_->toPlainText()));o.insert(QStringLiteral("counterpoint"),theoryCounterpoint_->toPlainText());o.insert(QStringLiteral("characterIds"),stringsJson(theoryCharacters_->text()));o.insert(QStringLiteral("tags"),stringsJson(theoryTags_->text()));a.replace(row,o);document_->setArray(QStringLiteral("theories"),a);theoryList_->item(row)->setText(theoryTitle_->text().isEmpty()?tr("Teoría sin título"):theoryTitle_->text());emit changed();}
void PlanningPage::addTheory(){if(!document_)return;QJsonArray a=document_->array(QStringLiteral("theories"));a.append(QJsonObject{{QStringLiteral("id"),uid(QStringLiteral("theory"))},{QStringLiteral("title"),tr("Nueva teoría")},{QStringLiteral("status"),tr("Abierta")},{QStringLiteral("confidence"),50},{QStringLiteral("thesis"),QString()},{QStringLiteral("evidence"),QJsonArray()},{QStringLiteral("counterpoint"),QString()},{QStringLiteral("characterIds"),QJsonArray()},{QStringLiteral("tags"),QJsonArray()}});document_->setArray(QStringLiteral("theories"),a);refreshTheories();theoryList_->setCurrentRow(a.size()-1);emit changed();}
void PlanningPage::removeTheory(){if(!document_)return;const int row=theoryList_->currentRow();QJsonArray a=document_->array(QStringLiteral("theories"));if(row<0||row>=a.size())return;a.removeAt(row);document_->setArray(QStringLiteral("theories"),a);refreshTheories();if(theoryList_->count())theoryList_->setCurrentRow(qMin(row,theoryList_->count()-1));emit changed();}
void PlanningPage::refreshTimeline(){timelineList_->clear();for(const QJsonValue v:document_->array(QStringLiteral("timeline"))){const QJsonObject e=v.toObject();timelineList_->addItem(QStringLiteral("%1 · %2 — %3").arg(e.value(QStringLiteral("chapter")).toString(),e.value(QStringLiteral("when")).toString(),e.value(QStringLiteral("title")).toString()));}}
void PlanningPage::selectTimeline(int row){if(!document_)return;refreshing_=true;const QJsonArray a=document_->array(QStringLiteral("timeline"));const QJsonObject e=row>=0&&row<a.size()?a.at(row).toObject():QJsonObject();timelineChapter_->setText(e.value(QStringLiteral("chapter")).toString());timelineWhen_->setText(e.value(QStringLiteral("when")).toString());timelineTitle_->setText(e.value(QStringLiteral("title")).toString());timelineSummary_->setPlainText(e.value(QStringLiteral("summary")).toString());timelineCharacters_->setText(jsonStrings(e.value(QStringLiteral("characterIds")).toArray()));timelineIntensity_->setValue(e.value(QStringLiteral("intensity")).toInt());refreshing_=false;}
void PlanningPage::applyTimeline(){if(refreshing_||!document_)return;const int row=timelineList_->currentRow();QJsonArray a=document_->array(QStringLiteral("timeline"));if(row<0||row>=a.size())return;QJsonObject e=a.at(row).toObject();e.insert(QStringLiteral("chapter"),timelineChapter_->text());e.insert(QStringLiteral("when"),timelineWhen_->text());e.insert(QStringLiteral("title"),timelineTitle_->text());e.insert(QStringLiteral("summary"),timelineSummary_->toPlainText());e.insert(QStringLiteral("characterIds"),stringsJson(timelineCharacters_->text()));e.insert(QStringLiteral("intensity"),timelineIntensity_->value());a.replace(row,e);document_->setArray(QStringLiteral("timeline"),a);refreshTimeline();timelineList_->setCurrentRow(row);emit changed();}
void PlanningPage::addTimeline(){if(!document_)return;QJsonArray a=document_->array(QStringLiteral("timeline"));a.append(QJsonObject{{QStringLiteral("id"),uid(QStringLiteral("timeline"))},{QStringLiteral("chapter"),QString()},{QStringLiteral("when"),QString()},{QStringLiteral("title"),tr("Nuevo evento")},{QStringLiteral("summary"),QString()},{QStringLiteral("characterIds"),QJsonArray()},{QStringLiteral("intensity"),1}});document_->setArray(QStringLiteral("timeline"),a);refreshTimeline();timelineList_->setCurrentRow(a.size()-1);emit changed();}
void PlanningPage::removeTimeline(){if(!document_)return;const int row=timelineList_->currentRow();QJsonArray a=document_->array(QStringLiteral("timeline"));if(row<0||row>=a.size())return;a.removeAt(row);document_->setArray(QStringLiteral("timeline"),a);refreshTimeline();if(timelineList_->count())timelineList_->setCurrentRow(qMin(row,timelineList_->count()-1));emit changed();}

} // namespace wbw
