<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>WorldbuilderWriter.RegressionTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WorldbuilderWriter.Core\WorldbuilderWriter.Core.csproj" />
    <ProjectReference Include="..\..\src\WorldbuilderWriter.Infrastructure\WorldbuilderWriter.Infrastructure.csproj" />
  </ItemGroup>
</Project>
