<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>WorldbuilderWriter.App</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WorldbuilderWriter.Core\WorldbuilderWriter.Core.csproj" />
    <ProjectReference Include="..\WorldbuilderWriter.Infrastructure\WorldbuilderWriter.Infrastructure.csproj" />
  </ItemGroup>
</Project>
